### ISSUE TITLE
安装不了呢？  求指导

### ISSUE THREAD

**Issue by Yinjianhua472392556** [ClaudeLi/IJKFramework#1]
安装不了呢？  求指导

**Comment by ClaudeLi** [comment]
> 安装不了呢？ 求指导

原来的私有库已启用，已推至公有库，update master 可直接 pod 'TTPlayerLib', '~> 1.2.0'

**Comment by ClaudeLi** [comment]
> 安装不了呢？ 求指导

原来的私有库已弃用，已推至公有库，update master 可直接 pod 'TTPlayerLib', '~> 1.2.0'
